export const transValidation = {
  email_incorrect: 'Email phải có dạng example@abc.com',
  password_incorrect: 'Mật khẩu chứa ít nhất 8 ký tự, bao gồm chữ hoa, chữ thường, chữ số và ký tự đặc biệt',
  password_confirmation_incorrect: 'Nhập lại mật khẩu không chính xác',
  username_incorrect: 'Tên không được chưa ký tự đặc biệt. Giới hạn 128 ký tự',
  address_incorrect: 'Địa chỉ giới hạn là 200 kí tự',
  update_phone: 'Số điện thoại Việt Nam bắt đầu bằng số 0, giới hạn trong khoảng 10 - 11 ký tự',
  sku_product: 'SKU chỉ bao gồm các kí tự chữ số',
  product_incorrect: 'Không thể chỉnh sửa sản phẩm này',
  catalog_incorrect: 'Sản phẩm này phải thuộc 1 danh mục',
  card_number: 'Số thẻ phải có dạng xxxx xxxx xxxx xxxx và chỉ chưa các ký tự số',
  account_number: 'Số tài khoản chỉ bao gồm chữ số và chữ hoa, không chứa ký tự đặc biệt. Giới hạn 8 - 16 ký tự',
  card_date: 'Ngày trên thẻ phải có dạng MM/YY',
  card_holder: 'Tên trên thẻ là tiếng Việt không dấu và chỉ gồm ký tự chữ hoa',
  bank: 'Tên ngân hàng không được để trống',
  not_allow_business: 'Bạn phải có giấy phép kinh doanh',
  business_code: 'Mã số kinh doanh chỉ gồm 10 ký tự số'
}

export const transError = {
  user_name_in_used: 'Tên đăng nhập này đã được sử dụng',
  account_non_active: 'Tài khoản của bạn đã bị khóa, hãy đăng nhập bằng tài khoản khác!',
  login_failed: 'Sai tài khoản hoặc mật khẩu.',
  authen_process: 'Xảy ra lỗi trong quá trình xác thực',
  require_login: 'Bạn phải đăng nhập để sử dụng chức năng này.',
  require_logout: 'Bạn phải đăng xuất trước.',
  register_failed: 'Tạo tài khoản không thành công. Xin kiểm tra lại',
  permission_denied: 'Bạn không có quyền thực hiện chức năng này',
  avatar_type: 'Kiểu file không hợp lệ, chỉ chấp nhận JPG hoặc PNG.',
  image_size: 'Kích thước ảnh tối đa là 2MB.',
  limit_file_upload: 'Số lượng file upload tối đa là 15.',
  add_product: 'Thêm sản phẩm mới thất bại.',
  register_provider: 'Đăng ký nhà cung cấp không thành công.',
  product_id_empty: 'Mã sản phẩm là bắt buộc.',
  product_id_not_existed: 'Không tìm thấy sản phẩm có mã #productId. Hãy kiểm tra lại.',
  catalog_id_empty: 'Mã nhóm vật tư là bắt buộc.',
  catalog_id_not_existed: 'Không tìm thấy vật tư có mã nhóm vật tư #categoryId. Hãy kiểm tra lại.',
  provider_id_empty: 'Mã nhà cung cấp là bắt buộc.',
  provider_id_not_existed: 'Không tìm thấy vật tư có mã nhà cung cấp #providerId. Hãy kiểm tra lại.',
  warehouse_id_empty: 'Mã kho là bắt buộc.',
  warehouse_id_not_existed: 'Không tìm thấy vật tư có mã kho #warehouseId. Hãy kiểm tra lại.',
  add_new_order: 'Thêm hóa đơn thất bại.',
  add_order_details: 'Có lỗi trong quá trình thêm sản phẩm vào hóa đơn',
  confirm_password_incorrect: 'Nhập lại mật khẩu không chính xác',
  password_incorrect: 'Mật khẩu cũ không chính xác',
  update_password: 'Đổi mật khẩu thất bại',
  add_employee: 'Thêm nhân viên mới thất bại.',
  add_product: 'Thêm vật tư mới thất bại.',
  add_category: 'Thêm nhóm vật tư mới thất bại',
  add_provider: 'Thêm nhà cung cấp mới thất bại',
  add_warehouse: 'Thêm kho mới thất bại',
  add_import_receipt: 'Thêm phiếu nhập kho thất bại',
  add_update_import_receipt_detail: 'Thêm chi tiết phiếu nhập kho thất bại',
  import_receipt_id_empty: 'Mã phiếu nhập là bắt buộc',
  import_receipt_id_not_existed: 'Không tìm thấy danh sách vật tư ở phiếu nhập có mã #receiptId. Hãy kiểm tra lại.',
  export_receipt_id_empty: 'Mã phiếu xuất là bắt buộc',
  export_receipt_id_not_existed: 'Không tìm thấy danh sách vật tư ở phiếu xuất có mã #receiptId. Hãy kiểm tra lại.',
  exchange_receipt_id_empty: 'Mã phiếu chuyển là bắt buộc',
  exchange_receipt_id_not_existed: 'Không tìm thấy danh sách vật tư ở phiếu chuyển có mã #receiptId. Hãy kiểm tra lại.',
  list_product_empty: 'Danh sách vật tư không được để trống',
  add_export_receipt: 'Thêm phiếu xuất kho thất bại',
  add_update_export_receipt_detail: 'Thêm chi tiết phiếu xuất kho thất bại',
  add_exchange_receipt: 'Thêm phiếu chuyển kho thất bại',
  add_update_exchange_receipt_detail: 'Thêm chi tiết phiếu chuyển kho thất bại',
}

export const transSuccess = {
  login: 'Đăng nhập thành công',
  logout: 'Đăng xuất thành công',
  register: 'Tài khoản đã được tạo thành công',
  add_product: 'Vật tư đã được thêm thành công',
  remove_product: 'Xóa vật tư thành công',
  update_product: 'Cập nhật vật tư thành công',
  register_provider: 'Đăng ký bán hàng thành công',
  approve_provider: 'Đã cấp quyền bán hàng cho nhà cung cấp',
  delete_provider: 'Đã xóa nhà cung cấp',
  update_password: 'Đổi mật khẩu thành công',
  add_employee: 'Nhân viên đã được thêm thành công',
  update_employee: 'Cập nhật nhân viên thành công',
  remove_employee: 'Xóa nhân viên thành công',
  add_category: 'Nhóm vật tư đã được thêm thành công',
  update_category: 'Cập nhật nhóm vật tư thành công',
  remove_category: 'Xóa nhóm vật tư thành công',
  add_provider: 'Nhà cung cấp đã được thêm thành công',
  update_provider: 'Cập nhật nhà cung cấp thành công',
  remove_provider: 'Xóa nhà cung cấp thành công',
  add_warehouse: 'Kho đã được thêm thành công',
  update_warehouse: 'Cập nhật kho thành công',
  remove_warehouse: 'Xóa kho thành công',
  add_import_good_receipt: 'Thêm phiếu nhập kho thành công',
  update_import_good_receipt: 'Cập nhật phiếu nhập kho thành công',
  add_export_good_receipt: 'Thêm phiếu xuất kho thành công',
  update_export_good_receipt: 'Cập nhật phiếu xuất kho thành công',
  add_exchange_good_receipt: 'Thêm phiếu chuyển kho thành công',
  update_exchange_good_receipt: 'Cập nhật phiếu chuyển kho thành công',
}
